In [1]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
x.shape

(2, 3)

In [12]:
n = np.arange(0, 40, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [13]:
n = n.reshape(4, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [15]:
m = np.linspace(0, 4, 9)
m

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [16]:
m.resize(3, 3)
m

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [17]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
y = np.array([1, 3, 7, 9])
np.diag(y)

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

In [24]:
np.repeat([1, 4, 5], 7)

array([1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5])

In [25]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [28]:
np.hstack([p, 2*p, 5*p])

array([[1, 1, 1, 2, 2, 2, 5, 5, 5],
       [1, 1, 1, 2, 2, 2, 5, 5, 5]])

In [29]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [33]:
s[4:]
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [35]:
s[-5::2] #forward

array([ 64, 100, 144], dtype=int32)

In [36]:
s[-5::-2] #backward

array([64, 36, 16,  4,  0], dtype=int32)

In [37]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [38]:
r[3, 3:6] #selecting 3rd array then slice

array([21, 22, 23])

In [39]:
r[:2, :-4]

array([[0, 1],
       [6, 7]])

In [2]:
import numpy as np
rand_arr = np.random.random([5, 3])
rand_arr

array([[0.59981914, 0.74856274, 0.51967624],
       [0.97301717, 0.20858558, 0.93875229],
       [0.53152427, 0.12903756, 0.41768695],
       [0.19536408, 0.32441782, 0.0171509 ],
       [0.1158047 , 0.10649504, 0.69001003]])

In [3]:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.6  , 0.749, 0.52 ],
       [0.973, 0.209, 0.939],
       [0.532, 0.129, 0.418],
       [0.195, 0.324, 0.017]])

In [5]:
mu, med, sd = np.mean(rand_arr), np.median(rand_arr), np.std(rand_arr)
print(mu, med, sd)

0.43439363454458413 0.4176869522246792 0.2999395985692074
